# Site settings
title: SenSys 2015
admin_name: NCLab
email:  cwcho@nclab.kaist.ac.kr
        sangwon@nclab.kaist.ac.kr
description: "SenSys is the leading conference for research on systems of networked sensing and actuation."

# baseurl: "/2014"

# url: "http://sensys.acm.org/2014/"

username: SenSys2015
location: Seoul, South Korea
dates: November 2-5, 2015

links:
    -   title: About
        url: /about/
    -   title: CFP
        url: /cfp/
    -   title: Organization
        url: /people/
    -   title: Venue
        url: /venue/
    -   title: ...
        url: /registration/
    -   title: ...
        url: /program/
    -   title: ...
        url: /demos/
    -   title: ...
        url: /workshops/
    -   title: ...
        url: /dc/
    -   title: ...
        url: /sponsors/


# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
